// ============================================================
// IMRAN MD BOT — ported commands (519)
// Auto-generated by /tmp/port.js — do not edit by hand.
// These 600 commands were ported from the Baileys prototype; every
// Baileys-specific action is adapted to the official WhatsApp Cloud API
// (text replies; graceful info-text where a Baileys client is required).
// ============================================================

const BOT_NAME = 'IMRAN MD BOT';
const OWNER_NAME = process.env.OWNER_NAME || 'Imran Salara';
const OWNER_NUMBER = '923046123264';
const OWNER_WA_LINK = 'https://wa.me/923046123264';

class BaileysUnavailable extends Error {}

function adapt(src, meta) {
  return {
    name: meta.name,
    description: src.desc || '',
    category: meta.category,
    usage: src.usage || ('.' + meta.name),
    aliases: meta.aliases,
    async execute(args, tctx) {
      const out = [];
      const push = (v) => { if (v !== undefined && v !== null && String(v).trim() !== '') out.push(String(v)); };
      const fakeSock = new Proxy({}, {
        get: (t, prop) => {
          if (prop === 'sendMessage') {
            return async (to, payload = {}) => {
              if (payload.text) push(payload.text);
              else if (payload.image && payload.image.url) {
                // Cloud API can send images by URL — return image result.
                throw { __imageResult: { text: payload.caption || '', image: payload.image.url } };
              } else if (payload.caption) push(payload.caption + '\n\n_(media preview not available on the official WhatsApp Cloud API)_');
              else if (payload.image || payload.video || payload.audio || payload.document) push('_(this media message is not supported on the official WhatsApp Cloud API)_');
              else if (payload.contacts) push('_(contact sharing is not supported on the official WhatsApp Cloud API)_');
              else if (payload.poll) push('📊 *Poll:* ' + (payload.name || ''));
              return {};
            };
          }
          if (prop === 'then') return undefined;
          return async () => { throw new BaileysUnavailable(String(prop)); };
        },
      });
      const all = tctx.commands || [];
      const fakeCtx = {
        args: args || [],
        text: (args || []).join(' '),
        from: tctx.from,
        sender: tctx.from,
        senderJid: tctx.from,
        msg: null,
        prefix: '.',
        isOwner: false,
        config: { botName: BOT_NAME, ownerName: OWNER_NAME, ownerNumber: OWNER_NUMBER },
        commands: all,
        categories() {
          const m = {};
          for (const c of all) {
            const k = c.category || 'general';
            (m[k] = m[k] || []).push({ cmd: c.name, name: c.name });
          }
          return m;
        },
        reply: async (v) => push(v),
        sock: fakeSock,
      };
      try {
        await src.run(fakeCtx);
      } catch (e) {
        if (e && e.__imageResult) return e.__imageResult;
        if (e instanceof BaileysUnavailable) {
          return 'ℹ️ _.' + meta.name + '_ needs WhatsApp features that are not available on the official Cloud API (this bot runs 1:1 chats, not groups).\n\n📋 Type .menu to see all ' + all.length + ' commands.\n📢 Channel: IMRAN SALARA MD Bot';
        }
        throw e;
      }
      const result = out.join('\n\n').trim();
      return result || null;
    },
  };
}

const META = [
 {
  "file": "ai.js",
  "idx": 5,
  "name": "dictionary",
  "aliases": [
   "meaning"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 6,
  "name": "synonyms",
  "aliases": [
   "syn"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 7,
  "name": "antonyms",
  "aliases": [
   "ant"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 8,
  "name": "rhyme",
  "aliases": [
   "kafiya"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 10,
  "name": "forecast",
  "aliases": [
   "peshgoi"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 11,
  "name": "pktime",
  "aliases": [
   "timepk",
   "waqt"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 13,
  "name": "wikiur",
  "aliases": [
   "wikiurdu"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 14,
  "name": "countryinfo",
  "aliases": [
   "country",
   "mulk"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 16,
  "name": "numberfact",
  "aliases": [
   "numfact"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 17,
  "name": "mathfact",
  "aliases": [
   "mfact"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 18,
  "name": "uselessfact",
  "aliases": [
   "ufact"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 19,
  "name": "advice",
  "aliases": [
   "nasihat",
   "mashwara"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 20,
  "name": "bored",
  "aliases": [
   "activity",
   "boriyat"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 21,
  "name": "github",
  "aliases": [
   "gh"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 22,
  "name": "repo",
  "aliases": [
   "ghrepo"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 23,
  "name": "npm",
  "aliases": [
   "npmpkg"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 24,
  "name": "namaz",
  "aliases": [
   "azaan"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 27,
  "name": "starsign",
  "aliases": [
   "zodiac"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 28,
  "name": "nameage",
  "aliases": [
   "agify"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 29,
  "name": "namegender",
  "aliases": [
   "genderize"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 30,
  "name": "nationality",
  "aliases": [
   "natio"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 31,
  "name": "dogpic",
  "aliases": [
   "dog"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 32,
  "name": "catpic",
  "aliases": [
   "cat"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 33,
  "name": "foxpic",
  "aliases": [
   "fox"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 34,
  "name": "duckpic",
  "aliases": [
   "duck"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 35,
  "name": "httpcat",
  "aliases": [
   "httpcode"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 36,
  "name": "itunes",
  "aliases": [
   "search"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 37,
  "name": "qrtext",
  "aliases": [],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 38,
  "name": "tinyurl",
  "aliases": [
   "short"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 39,
  "name": "unshorten",
  "aliases": [
   "expand"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 41,
  "name": "upper",
  "aliases": [
   "up"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 42,
  "name": "lower",
  "aliases": [
   "low"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 43,
  "name": "title",
  "aliases": [
   "capitalize"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 46,
  "name": "vaporwave",
  "aliases": [
   "vapor"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 49,
  "name": "unmorse",
  "aliases": [
   "demorse"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 51,
  "name": "unbinary",
  "aliases": [
   "debin"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 52,
  "name": "base64e",
  "aliases": [
   "b64e"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 53,
  "name": "base64d",
  "aliases": [
   "b64d"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 58,
  "name": "palindrome",
  "aliases": [
   "palin"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 60,
  "name": "zalgo",
  "aliases": [
   "cursed"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 61,
  "name": "strike",
  "aliases": [
   "strikethrough"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 62,
  "name": "smallcaps",
  "aliases": [
   "scaps"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 63,
  "name": "fliptext",
  "aliases": [
   "flip"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 66,
  "name": "pin",
  "aliases": [
   "otpgen"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 67,
  "name": "pick",
  "aliases": [],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 68,
  "name": "diceroll",
  "aliases": [],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 69,
  "name": "cointoss",
  "aliases": [
   "toss"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 70,
  "name": "math",
  "aliases": [
   "hisaab"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 71,
  "name": "prime",
  "aliases": [
   "isprime"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 72,
  "name": "fibonacci",
  "aliases": [
   "fib"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 73,
  "name": "factorial",
  "aliases": [
   "factn"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 74,
  "name": "bmi",
  "aliases": [
   "sehat"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 75,
  "name": "agecalc",
  "aliases": [
   "age"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 76,
  "name": "percent",
  "aliases": [
   "pct"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 77,
  "name": "average",
  "aliases": [
   "avg"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 78,
  "name": "temp",
  "aliases": [
   "temperature"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 79,
  "name": "unit",
  "aliases": [
   "convertunit"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 81,
  "name": "remindme",
  "aliases": [
   "remind",
   "yad"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 83,
  "name": "lorem",
  "aliases": [
   "dummytext"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 84,
  "name": "serverip",
  "aliases": [
   "myip"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 85,
  "name": "chuck",
  "aliases": [
   "chucknorris"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 86,
  "name": "dadjoke",
  "aliases": [
   "dad"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 87,
  "name": "kanye",
  "aliases": [
   "kanyequote"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 88,
  "name": "nickname",
  "aliases": [
   "nick"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 89,
  "name": "username",
  "aliases": [
   "uname"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 90,
  "name": "geocode",
  "aliases": [
   "latlong",
   "coords"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 91,
  "name": "elevation",
  "aliases": [
   "height",
   "bulandi"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 92,
  "name": "aqi",
  "aliases": [
   "airquality",
   "fiza"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 94,
  "name": "eightball",
  "aliases": [
   "magicball"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 95,
  "name": "lovecalc",
  "aliases": [],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 97,
  "name": "roastme",
  "aliases": [],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 98,
  "name": "motivate",
  "aliases": [
   "himmat"
  ],
  "category": "ai & fun"
 },
 {
  "file": "ai.js",
  "idx": 99,
  "name": "ship",
  "aliases": [
   "jori"
  ],
  "category": "ai & fun"
 },
 {
  "file": "download.js",
  "idx": 1,
  "name": "gaana",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 2,
  "name": "mp3",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 3,
  "name": "play",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 4,
  "name": "track",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 5,
  "name": "tune",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 6,
  "name": "music",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 7,
  "name": "audio",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 8,
  "name": "ytaudio",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 9,
  "name": "ytmp3",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 10,
  "name": "ytmp4",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 11,
  "name": "ytvideo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 12,
  "name": "ytdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 13,
  "name": "ytsearch",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 14,
  "name": "yts",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 15,
  "name": "video",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 16,
  "name": "mp4",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 17,
  "name": "clip",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 18,
  "name": "mv",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 20,
  "name": "tikdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 21,
  "name": "tt",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 22,
  "name": "ttaudio",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 23,
  "name": "ttvideo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 24,
  "name": "ttslide",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 26,
  "name": "fbvideo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 27,
  "name": "fbaudio",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 28,
  "name": "fbwatch",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 29,
  "name": "instadl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 30,
  "name": "instavid",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 31,
  "name": "instareel",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 32,
  "name": "instaimg",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 33,
  "name": "igdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 35,
  "name": "tweetdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 36,
  "name": "xdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 38,
  "name": "lyric",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 39,
  "name": "gaanalyrics",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 40,
  "name": "itunessong",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 41,
  "name": "itunes2",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 42,
  "name": "applesong",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 43,
  "name": "preview",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 44,
  "name": "podcast",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 45,
  "name": "podcastsearch",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 46,
  "name": "podcastep",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 48,
  "name": "animeinfo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 49,
  "name": "manga",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 50,
  "name": "mangainfo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 51,
  "name": "animechar",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 53,
  "name": "wallpaperhd",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 54,
  "name": "mobilewall",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 55,
  "name": "pcwall",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 56,
  "name": "naturewall",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 57,
  "name": "darkwall",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 58,
  "name": "movieinfo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 59,
  "name": "findmovie",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 60,
  "name": "moviesearch",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 61,
  "name": "movietrailer",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 62,
  "name": "filminfo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 63,
  "name": "drama",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 64,
  "name": "dramaep",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 65,
  "name": "dramainfo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 66,
  "name": "pakdrama",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 67,
  "name": "qawwali",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 68,
  "name": "naat",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 69,
  "name": "nasheed",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 70,
  "name": "ghazal",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 71,
  "name": "punjabisong",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 72,
  "name": "hindisong",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 73,
  "name": "sadsong",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 74,
  "name": "djsong",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 75,
  "name": "remix",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 76,
  "name": "lofi",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 78,
  "name": "audiobook",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 80,
  "name": "scdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 81,
  "name": "spotify",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 82,
  "name": "spotisearch",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 83,
  "name": "ytthumb",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 84,
  "name": "vimeoinfo",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 85,
  "name": "pindl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 86,
  "name": "pinimg",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 87,
  "name": "likeedl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 88,
  "name": "snackdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 89,
  "name": "rumbledl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 90,
  "name": "mediadl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 91,
  "name": "gdrivedl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 92,
  "name": "apkdl",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 93,
  "name": "tiktrend",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 94,
  "name": "yttrend",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 96,
  "name": "topsongs",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 97,
  "name": "newrelease",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 98,
  "name": "topalbums",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "download.js",
  "idx": 99,
  "name": "radiolive",
  "aliases": [],
  "category": "downloaders"
 },
 {
  "file": "fun.js",
  "idx": 1,
  "name": "latifa",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 3,
  "name": "sher",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 4,
  "name": "ghazal2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 5,
  "name": "rubai",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 6,
  "name": "mushaira",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 8,
  "name": "motivate2",
  "aliases": [
   "joshtak"
  ],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 9,
  "name": "success",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 10,
  "name": "wisdom",
  "aliases": [
   "danaai"
  ],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 11,
  "name": "deep",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 12,
  "name": "shower",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 14,
  "name": "didyouknow",
  "aliases": [
   "dyk"
  ],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 15,
  "name": "trivia",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 16,
  "name": "quiz",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 18,
  "name": "paheli2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 19,
  "name": "puzzle",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 20,
  "name": "teaser",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 21,
  "name": "eightball2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 22,
  "name": "magic",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 25,
  "name": "roll2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 28,
  "name": "lotto",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 29,
  "name": "lucky",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 30,
  "name": "stars",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 31,
  "name": "zodiac2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 32,
  "name": "love2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 33,
  "name": "friendship",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 36,
  "name": "wyr",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 37,
  "name": "nhie",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 38,
  "name": "secret",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 39,
  "name": "compliment2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 41,
  "name": "roast2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 42,
  "name": "comeback",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 44,
  "name": "dadjoke2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 45,
  "name": "knock",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 46,
  "name": "pun",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 47,
  "name": "oneline",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 48,
  "name": "kidjoke",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 49,
  "name": "doctor",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 50,
  "name": "teacher",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 51,
  "name": "student",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 52,
  "name": "husband",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 53,
  "name": "biwi",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 54,
  "name": "office",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 55,
  "name": "desi",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 56,
  "name": "emojital",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 58,
  "name": "moral",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 59,
  "name": "kahani",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 60,
  "name": "kahawat",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 61,
  "name": "muhawara",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 62,
  "name": "proverb",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 63,
  "name": "idiom",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 64,
  "name": "twister",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 65,
  "name": "uljhan",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 66,
  "name": "allit",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 67,
  "name": "rhyme2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 68,
  "name": "rap",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 69,
  "name": "geet",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 70,
  "name": "fdialog",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 71,
  "name": "birthday",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 72,
  "name": "gm",
  "aliases": [
   "goodmorning"
  ],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 73,
  "name": "gn",
  "aliases": [
   "goodnight"
  ],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 74,
  "name": "eid",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 75,
  "name": "shaadi",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 76,
  "name": "exam",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 77,
  "name": "sorry",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 78,
  "name": "thanksmsg",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 79,
  "name": "missu",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 80,
  "name": "bff",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 81,
  "name": "nickname2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 82,
  "name": "superpower",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 83,
  "name": "future",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 84,
  "name": "past",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 85,
  "name": "dream",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 86,
  "name": "vibe",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 87,
  "name": "mood",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 88,
  "name": "color2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 89,
  "name": "day",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 90,
  "name": "hafta",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 91,
  "name": "advice2",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 93,
  "name": "challenge",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 94,
  "name": "game",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 95,
  "name": "score",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 96,
  "name": "rate",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 97,
  "name": "filmy",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 98,
  "name": "chai",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "fun.js",
  "idx": 99,
  "name": "party",
  "aliases": [],
  "category": "fun"
 },
 {
  "file": "general.js",
  "idx": 5,
  "name": "botinfo",
  "aliases": [
   "binfo"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 10,
  "name": "day2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 11,
  "name": "weekday",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 12,
  "name": "month",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 13,
  "name": "year",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 14,
  "name": "timestamp",
  "aliases": [
   "ts"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 15,
  "name": "unixtime",
  "aliases": [
   "unix"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 19,
  "name": "myjid",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 20,
  "name": "chat",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 22,
  "name": "totalcmds",
  "aliases": [
   "total"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 23,
  "name": "categories",
  "aliases": [
   "cats"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 24,
  "name": "search2",
  "aliases": [
   "find"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 25,
  "name": "cmdinfo",
  "aliases": [
   "cinfo"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 26,
  "name": "repo2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 30,
  "name": "source",
  "aliases": [
   "src"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 33,
  "name": "latency",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 34,
  "name": "starttime",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 35,
  "name": "sysinfo",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 36,
  "name": "memory",
  "aliases": [
   "mem"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 37,
  "name": "platform",
  "aliases": [
   "os"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 38,
  "name": "nodever",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 39,
  "name": "cpu",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 40,
  "name": "profile",
  "aliases": [
   "pp"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 41,
  "name": "about",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 42,
  "name": "terms",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 43,
  "name": "privacy",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 44,
  "name": "contact",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 45,
  "name": "feedback",
  "aliases": [
   "fb"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 46,
  "name": "suggest",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 47,
  "name": "report",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 48,
  "name": "echo",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 49,
  "name": "say",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 50,
  "name": "repeat",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 51,
  "name": "reverse2",
  "aliases": [
   "rev"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 52,
  "name": "upper2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 53,
  "name": "lower2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 54,
  "name": "shuffle",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 55,
  "name": "sort",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 56,
  "name": "count",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 57,
  "name": "words",
  "aliases": [
   "wc"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 58,
  "name": "chars",
  "aliases": [
   "cc"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 59,
  "name": "lines",
  "aliases": [
   "lc"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 60,
  "name": "vowels",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 61,
  "name": "consonants",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 62,
  "name": "palindrome2",
  "aliases": [
   "pal"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 63,
  "name": "ascii",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 64,
  "name": "binary2",
  "aliases": [
   "bin"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 65,
  "name": "morse2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 66,
  "name": "unmorse2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 67,
  "name": "b64e2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 68,
  "name": "b64d2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 69,
  "name": "urlencode2",
  "aliases": [
   "urle"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 70,
  "name": "urldecode2",
  "aliases": [
   "urld"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 71,
  "name": "sha256",
  "aliases": [
   "sha"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 72,
  "name": "md5",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 73,
  "name": "uuid2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 74,
  "name": "password2",
  "aliases": [
   "pass",
   "genpass"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 75,
  "name": "rand",
  "aliases": [
   "randomnum"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 76,
  "name": "flip2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 77,
  "name": "roll2x",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 78,
  "name": "choose2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 79,
  "name": "yesno",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 80,
  "name": "percent2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 81,
  "name": "rate2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 82,
  "name": "love2x",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 83,
  "name": "timer2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 84,
  "name": "remind2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 85,
  "name": "age2",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 86,
  "name": "countdown",
  "aliases": [
   "cdown"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 87,
  "name": "weekdayof",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 88,
  "name": "daysbetween",
  "aliases": [
   "dbetween"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 89,
  "name": "status",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 90,
  "name": "groups",
  "aliases": [
   "grouplist",
   "mygroups"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 91,
  "name": "blocklist",
  "aliases": [
   "blocks"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 92,
  "name": "setname",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 93,
  "name": "setbio",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 94,
  "name": "restart",
  "aliases": [
   "reboot"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 96,
  "name": "emojify2",
  "aliases": [
   "emoji"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 97,
  "name": "shortmenu",
  "aliases": [
   "smenu"
  ],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 98,
  "name": "changelog",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "general.js",
  "idx": 99,
  "name": "credits",
  "aliases": [],
  "category": "general"
 },
 {
  "file": "group.js",
  "idx": 0,
  "name": "tagall",
  "aliases": [
   "everyoneall"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 1,
  "name": "hidetag",
  "aliases": [
   "htag"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 2,
  "name": "tagadmins",
  "aliases": [
   "admins2"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 3,
  "name": "admins",
  "aliases": [
   "adminlist"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 4,
  "name": "members",
  "aliases": [
   "memberlist"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 5,
  "name": "everyone",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 6,
  "name": "tag",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 7,
  "name": "stag",
  "aliases": [
   "silents"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 8,
  "name": "tagone",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 9,
  "name": "report2",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 10,
  "name": "kick",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 11,
  "name": "add",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 12,
  "name": "promote",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 13,
  "name": "demote",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 14,
  "name": "softkick",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 15,
  "name": "warn",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 16,
  "name": "warns",
  "aliases": [
   "warnlist"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 17,
  "name": "unwarn",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 18,
  "name": "resetwarns",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 19,
  "name": "purgewarned",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 20,
  "name": "mute",
  "aliases": [
   "announce",
   "readonly",
   "close2"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 21,
  "name": "unmute",
  "aliases": [
   "chat2",
   "open2"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 22,
  "name": "lock",
  "aliases": [
   "seal",
   "private2"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 23,
  "name": "unlock",
  "aliases": [
   "unseal",
   "public2",
   "open3"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 24,
  "name": "timedmute",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 25,
  "name": "ephemeral",
  "aliases": [
   "disappearing"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 26,
  "name": "noephemeral",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 27,
  "name": "setname2",
  "aliases": [
   "setsubject",
   "rename"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 28,
  "name": "setdesc",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 29,
  "name": "gsettings",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 30,
  "name": "groupinfo",
  "aliases": [
   "ginfo"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 31,
  "name": "gcount",
  "aliases": [
   "membercount",
   "total2"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 32,
  "name": "gname",
  "aliases": [
   "groupname"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 33,
  "name": "gdesc",
  "aliases": [
   "groupdesc"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 34,
  "name": "gid",
  "aliases": [
   "groupid"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 35,
  "name": "gpic",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 37,
  "name": "created",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 38,
  "name": "gowner",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 39,
  "name": "whois",
  "aliases": [
   "memberinfo"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 40,
  "name": "invite",
  "aliases": [
   "getlink",
   "invitelink2"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 42,
  "name": "revoke",
  "aliases": [
   "resetlink"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 43,
  "name": "newlink",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 44,
  "name": "checklink",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 45,
  "name": "inviteinfo",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 46,
  "name": "join",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 47,
  "name": "leave",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 48,
  "name": "creategroup",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 49,
  "name": "glist",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 50,
  "name": "requests",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 51,
  "name": "approve",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 52,
  "name": "reject",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 53,
  "name": "approveall",
  "aliases": [
   "acceptall"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 54,
  "name": "rejectall",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 56,
  "name": "del",
  "aliases": [
   "delete2"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 57,
  "name": "botadmin",
  "aliases": [
   "checkadmin"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 58,
  "name": "amadmin",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 59,
  "name": "isadmin",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 60,
  "name": "antilink",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 61,
  "name": "antiforeign",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 62,
  "name": "antisticker",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 63,
  "name": "antiporn",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 64,
  "name": "filter",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 65,
  "name": "addfilter",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 66,
  "name": "delfilter",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 67,
  "name": "filters",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 68,
  "name": "modstatus",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 69,
  "name": "kickall",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 70,
  "name": "welcome",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 71,
  "name": "goodbye",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 72,
  "name": "setwelcome",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 73,
  "name": "setgoodbye",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 74,
  "name": "greet",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 75,
  "name": "bye",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 76,
  "name": "rules2",
  "aliases": [
   "rule"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 77,
  "name": "setrules",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 78,
  "name": "notes",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 79,
  "name": "addnote",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 80,
  "name": "getnote",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 81,
  "name": "delnote",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 82,
  "name": "afk",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 83,
  "name": "unafk",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 84,
  "name": "afklist",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 85,
  "name": "broadcast",
  "aliases": [
   "bc"
  ],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 86,
  "name": "promoteall",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 87,
  "name": "demoteall",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 88,
  "name": "remind2x",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 89,
  "name": "alert",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 90,
  "name": "typing",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 91,
  "name": "recording",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 92,
  "name": "presence",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 93,
  "name": "vcard",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 94,
  "name": "wiki2",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 95,
  "name": "currency2",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 96,
  "name": "prayer2",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 97,
  "name": "limits",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 98,
  "name": "ghelp",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "group.js",
  "idx": 99,
  "name": "sendto",
  "aliases": [],
  "category": "group"
 },
 {
  "file": "islamic.js",
  "idx": 1,
  "name": "dua-safar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 2,
  "name": "dua-khana",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 3,
  "name": "dua-khana-baad",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 4,
  "name": "dua-sona",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 5,
  "name": "dua-uthna",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 6,
  "name": "dua-pareshani",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 7,
  "name": "dua-bimari",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 8,
  "name": "dua-rizq",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 9,
  "name": "dua-imtihan",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 10,
  "name": "dua-barish",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 11,
  "name": "dua-ghar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 12,
  "name": "dua-bahar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 13,
  "name": "dua-masjid",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 14,
  "name": "dua-wuzu",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 15,
  "name": "dua-iftar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 16,
  "name": "dua-sehri",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 17,
  "name": "dua-nikah",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 18,
  "name": "dua-aulad",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 19,
  "name": "dua-mayyat",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 20,
  "name": "dua-qarz",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 21,
  "name": "dua-gussa",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 22,
  "name": "dua-khauf",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 23,
  "name": "dua-shifa",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 24,
  "name": "dua-hajat",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 25,
  "name": "dua-istikhara",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 26,
  "name": "dua-toba",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 27,
  "name": "dua-juma",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 28,
  "name": "dua-subah",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 29,
  "name": "dua-sham",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 30,
  "name": "ayatul-kursi",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 31,
  "name": "surah-fatiha",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 32,
  "name": "surah-ikhlas",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 33,
  "name": "surah-falaq",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 34,
  "name": "surah-nas",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 35,
  "name": "surah-kausar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 36,
  "name": "surah-asr",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 37,
  "name": "surah-fil",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 38,
  "name": "surah-quraish",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 39,
  "name": "surah-maun",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 40,
  "name": "surah-lahab",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 41,
  "name": "surah-yasin",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 42,
  "name": "surah-rahman",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 43,
  "name": "surah-mulk",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 44,
  "name": "surah-kahf",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 45,
  "name": "surah-waqiah",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 46,
  "name": "surah-dukhan",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 47,
  "name": "surah-muzzammil",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 48,
  "name": "surah-humazah",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 49,
  "name": "surah-takathur",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 50,
  "name": "asma1",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 51,
  "name": "asma2",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 52,
  "name": "asma3",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 53,
  "name": "asma4",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 54,
  "name": "asma5",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 55,
  "name": "kalma1",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 56,
  "name": "kalma2",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 57,
  "name": "kalma3",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 58,
  "name": "kalma4",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 59,
  "name": "kalma5",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 60,
  "name": "kalma6",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 62,
  "name": "hadith-ilm",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 63,
  "name": "hadith-akhlaq",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 64,
  "name": "hadith-namaz",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 65,
  "name": "hadith-sabr",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 66,
  "name": "seerah",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 67,
  "name": "seerah-makkah",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 68,
  "name": "seerah-madina",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 69,
  "name": "seerah-hijrat",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 70,
  "name": "seerah-ghazwat",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 71,
  "name": "sahaba",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 72,
  "name": "abubakar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 73,
  "name": "umar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 74,
  "name": "usman",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 75,
  "name": "ali",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 77,
  "name": "darood-ibrahimi",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 78,
  "name": "darood-fazilat",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 79,
  "name": "darood-taj",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 80,
  "name": "namaz2",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 81,
  "name": "roza",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 83,
  "name": "hajj",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 84,
  "name": "umrah",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 85,
  "name": "qibla2",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 87,
  "name": "istighfar",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 89,
  "name": "sunnat",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 91,
  "name": "qadr",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 92,
  "name": "taraweeh",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 93,
  "name": "fitr",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 94,
  "name": "juma",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 95,
  "name": "eid2",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 96,
  "name": "tahajjud",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 97,
  "name": "ishraq",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 98,
  "name": "muharram",
  "aliases": [],
  "category": "islamic"
 },
 {
  "file": "islamic.js",
  "idx": 99,
  "name": "shaban",
  "aliases": [],
  "category": "islamic"
 }
];

const adapted = META.map((m) => {
  const arr = require('./vendor/' + m.file);
  return adapt(arr[m.idx], m);
});

module.exports = adapted;
